import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { afterAll, describe, expect, it } from 'vitest';

import {
  filterDenylistedSlugs,
  loadRestoreDenylist,
} from '../scripts/backfill-prev-slugs-from-loss-events.mjs';
import { foreignSigForSlug } from '../scripts/build-prev-slug-restore-denylist.mjs';

// Regression tests for issue #4061 / recovery run 29106416912 (commit
// efed987db "Recover 352 previousSlugs across 98 jobs"): the #4055 umantis
// cross-tenant decontamination (squash 028d6c1147) deliberately deleted
// foreign companies' slugs from 15 by-crawler slices' previousSlugs
// histories. scan-prev-slug-losses.mjs cannot distinguish an intentional
// removal from an accidental loss, so the very next scheduled recovery run
// counted the decontamination as "421 losses" and re-imported the poison
// (7 ksa jobs got kanton-aargau/GKB slugs back). The guard: intentionally
// removed (file, slug) pairs live in data/prev-slug-restore-denylist.json
// (generated by scripts/build-prev-slug-restore-denylist.mjs) and the
// backfill skips them before restoring anything.

const tmpFiles: string[] = [];
afterAll(() => {
  for (const f of tmpFiles) fs.rmSync(f, { force: true });
});

function writeTmpDenylist(payload: unknown): string {
  const f = path.join(os.tmpdir(), `denylist-guard-test-${process.pid}-${tmpFiles.length}.json`);
  fs.writeFileSync(f, JSON.stringify(payload));
  tmpFiles.push(f);
  return f;
}

const POISON = {
  file: 'ksa.json',
  jobId: 'ksa-fdd20d71aa74',
  slug: 'rechtspraktikant-rechtspraktikantin-100-kanton-aargau-ch',
};

describe('loadRestoreDenylist', () => {
  it('returns an empty set (guard off, no crash) when the file is missing', () => {
    const set = loadRestoreDenylist('/nonexistent/prev-slug-restore-denylist.json');
    expect(set.size).toBe(0);
  });

  it('throws on a present-but-corrupt file instead of silently disabling the guard', () => {
    const f = writeTmpDenylist({});
    fs.writeFileSync(f, '{ not json');
    expect(() => loadRestoreDenylist(f)).toThrow();
  });

  it('indexes entries by file+slug', () => {
    const f = writeTmpDenylist({ entries: [POISON] });
    const set = loadRestoreDenylist(f);
    expect(set.has(`${POISON.file}\u0000${POISON.slug}`)).toBe(true);
    expect(set.size).toBe(1);
  });

  it('loads the committed data file and knows the re-imported ksa poison', () => {
    const set = loadRestoreDenylist();
    expect(set.size).toBeGreaterThan(0);
    // Pair verified re-imported by run 29106416912 onto ksa-fdd20d71aa74.
    expect(set.has(`${POISON.file}\u0000${POISON.slug}`)).toBe(true);
    // Censused garbage-title slugs are denylisted too.
    expect(set.has('ksa.json\u0000vor-ort-letter-in-ikt-unterstutzung-kantonsspital-aarau-ksa-aarau')).toBe(true);
    expect(set.has('ksa.json\u0000logi-hyardfachfrau-hyardfachmann-kantonsspital-aarau-ksa-aarau-23121f')).toBe(true);
    // Allianz purge (1472959f74) removals re-imported by the same run into
    // sanatorium-kilchberg.json are covered too.
    expect(set.has('sanatorium-kilchberg.json\u0000allianz-bewerbermanagement-allianz-suisse-echallens')).toBe(true);
  });
});

describe('filterDenylistedSlugs', () => {
  const denylist = new Set([
    `${POISON.file}\u0000${POISON.slug}`,
  ]);

  it('drops a denylisted pair but keeps a normal pair on the same job', () => {
    const recoverList = [
      { jobId: POISON.jobId, file: POISON.file, slugs: [POISON.slug, 'dipl-radiologiefachfrau-kantonsspital-aarau-ksa-aarau'] },
    ];
    const { entries, skipped } = filterDenylistedSlugs(recoverList, denylist);
    expect(skipped).toBe(1);
    expect(entries).toEqual([
      { jobId: POISON.jobId, file: POISON.file, slugs: ['dipl-radiologiefachfrau-kantonsspital-aarau-ksa-aarau'] },
    ]);
  });

  it('matches on file+slug regardless of jobId — recovery can re-home poison onto another job of the same slice', () => {
    // Run 29106416912 spread one denylisted ksa slug across three different
    // jobs via the hash-tail redirect; the guard must not depend on the
    // provenance jobId.
    const recoverList = [
      { jobId: 'ksa-somethingelse', file: POISON.file, slugs: [POISON.slug] },
    ];
    const { entries, skipped } = filterDenylistedSlugs(recoverList, denylist);
    expect(skipped).toBe(1);
    expect(entries).toEqual([]);
  });

  it('does not drop the same slug when it belongs to a different slice file', () => {
    const recoverList = [
      { jobId: 'kanton-aargau-x', file: 'kanton-aargau.json', slugs: [POISON.slug] },
    ];
    const { entries, skipped } = filterDenylistedSlugs(recoverList, denylist);
    expect(skipped).toBe(0);
    expect(entries).toEqual(recoverList);
  });

  it('is a no-op passthrough with an empty denylist', () => {
    const recoverList = [{ jobId: 'a', file: 'b.json', slugs: ['c'] }];
    const { entries, skipped } = filterDenylistedSlugs(recoverList, new Set());
    expect(skipped).toBe(0);
    expect(entries).toBe(recoverList);
  });
});

describe('foreignSigForSlug (denylist derivation rule)', () => {
  it('flags a kanton-aargau slug inside ksa.json as foreign', () => {
    expect(foreignSigForSlug('ksa.json', POISON.slug)).toBe('kanton-aargau');
  });

  it('flags a GKB slug inside ksa.json as foreign', () => {
    expect(foreignSigForSlug('ksa.json', 'valutatore-immobiliare-graubundner-kantonalbank-chur')).toBe('gkb');
  });

  it('does not flag the slice own-company slug', () => {
    expect(foreignSigForSlug('ksa.json', 'dipl-radiologiefachfrau-radiologiefachmann-kantonsspital-aarau-ksa-aarau')).toBeNull();
    expect(foreignSigForSlug('kanton-aargau.json', 'schulpsychologin-schulpsychologe-80-kanton-aargau-ch')).toBeNull();
  });

  it('does not flag a signature-free slug anywhere', () => {
    expect(foreignSigForSlug('ksa.json', 'random-junior-developer-position')).toBeNull();
  });
});
