import { describe, expect, it } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';

/**
 * Regression test for the GSC "Pagina con reindirizzamento" issue.
 *
 * Root cause: flat .html files (e.g. `slug.html`) generated by build plugins
 * contained `location.replace()` JS redirects.  Google treated these as
 * "Page with redirect" and refused to index them.
 *
 * The flatContentPlugin replaces these with copies of the corresponding
 * `slug/index.html` content so both `/slug` and `/slug/` serve identical
 * pages with canonical consolidation.
 */

/* ── Helper: simulate the flatContentPlugin logic ──────────── */
function replaceRedirectFlats(distDir: string): { replaced: number; skipped: number } {
  let replaced = 0;
  let skipped = 0;

  const walk = (dir: string) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        walk(path.join(dir, entry.name));
        continue;
      }
      if (
        !entry.name.endsWith('.html') ||
        entry.name === 'index.html' ||
        entry.name === '404.html'
      ) continue;

      const flatPath = path.join(dir, entry.name);
      const content = fs.readFileSync(flatPath, 'utf-8');

      if (!content.includes('location.replace(')) {
        skipped++;
        continue;
      }

      const baseName = entry.name.replace(/\.html$/, '');
      const indexPath = path.join(dir, baseName, 'index.html');

      if (fs.existsSync(indexPath)) {
        fs.copyFileSync(indexPath, flatPath);
        replaced++;
      } else {
        skipped++;
      }
    }
  };

  walk(distDir);
  return { replaced, skipped };
}

describe('flat-content-duplicator (GSC redirect fix)', () => {
  it('replaces flat redirect files with index.html content', () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flat-content-'));

    // Create a flat redirect file
    const articleDir = path.join(tmpDir, 'articoli-frontaliere');
    fs.mkdirSync(articleDir, { recursive: true });
    fs.writeFileSync(
      path.join(articleDir, 'test-article.html'),
      `<!DOCTYPE html><html><head><link rel="canonical" href="x"><script>location.replace('/articoli-frontaliere/test-article/')</script></head><body></body></html>`,
    );

    // Create the corresponding index.html with full content
    const indexDir = path.join(articleDir, 'test-article');
    fs.mkdirSync(indexDir, { recursive: true });
    fs.writeFileSync(
      path.join(indexDir, 'index.html'),
      `<!DOCTYPE html><html><head><title>Test Article</title><link rel="canonical" href="https://frontaliereticino.ch/articoli-frontaliere/test-article/"></head><body><article>Full content</article></body></html>`,
    );

    const result = replaceRedirectFlats(tmpDir);

    expect(result.replaced).toBe(1);
    const flatContent = fs.readFileSync(path.join(articleDir, 'test-article.html'), 'utf-8');
    expect(flatContent).toContain('<article>Full content</article>');
    expect(flatContent).not.toContain('location.replace(');

    // Cleanup
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('does not touch flat files without location.replace()', () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flat-content-'));

    const dir = path.join(tmpDir, 'test');
    fs.mkdirSync(dir, { recursive: true });
    // Bridge page without JS redirect (e.g. buildCanonicalBridgePage output)
    fs.writeFileSync(
      path.join(dir, 'expired-job.html'),
      `<!DOCTYPE html><html><head><link rel="canonical" href="x"></head><body>Job expired</body></html>`,
    );
    fs.mkdirSync(path.join(dir, 'expired-job'), { recursive: true });
    fs.writeFileSync(path.join(dir, 'expired-job', 'index.html'), '<html>content</html>');

    const result = replaceRedirectFlats(tmpDir);
    expect(result.skipped).toBe(1);
    expect(result.replaced).toBe(0);

    const flatContent = fs.readFileSync(path.join(dir, 'expired-job.html'), 'utf-8');
    expect(flatContent).toContain('Job expired');  // unchanged

    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('skips flat files with no corresponding index.html', () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flat-content-'));

    const dir = path.join(tmpDir, 'orphan');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
      path.join(dir, 'orphan.html'),
      `<!DOCTYPE html><html><head><script>location.replace('/orphan/')</script></head><body></body></html>`,
    );
    // No orphan/index.html directory created

    const result = replaceRedirectFlats(tmpDir);
    expect(result.skipped).toBe(1);
    expect(result.replaced).toBe(0);

    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('skips index.html and 404.html', () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flat-content-'));

    fs.writeFileSync(path.join(tmpDir, 'index.html'), `<script>location.replace('/')</script>`);
    fs.writeFileSync(path.join(tmpDir, '404.html'), `<script>location.replace('/')</script>`);

    const result = replaceRedirectFlats(tmpDir);
    expect(result.replaced).toBe(0);
    expect(result.skipped).toBe(0); // these are filtered out, not counted as skipped

    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('handles nested locale paths correctly', () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flat-content-'));

    // Create nested: en/cross-border-articles/test-article.html
    const localeDir = path.join(tmpDir, 'en', 'cross-border-articles');
    fs.mkdirSync(localeDir, { recursive: true });
    fs.writeFileSync(
      path.join(localeDir, 'test-article.html'),
      `<html><head><script>location.replace('/en/cross-border-articles/test-article/')</script></head></html>`,
    );
    // Create corresponding index.html
    const indexDir = path.join(localeDir, 'test-article');
    fs.mkdirSync(indexDir, { recursive: true });
    fs.writeFileSync(path.join(indexDir, 'index.html'), '<html><body>EN content</body></html>');

    const result = replaceRedirectFlats(tmpDir);
    expect(result.replaced).toBe(1);
    const flat = fs.readFileSync(path.join(localeDir, 'test-article.html'), 'utf-8');
    expect(flat).toContain('EN content');
    expect(flat).not.toContain('location.replace(');

    fs.rmSync(tmpDir, { recursive: true, force: true });
  });
});
