import { getLocale, type Locale } from '@/services/i18n';

// FRO-336: Import build-time Amazon product data (generated by fetch-amazon-products.mjs)
import amazonProductsData from '@/data/amazon-products.json';

interface AmazonProductEntry {
  asin: string;
  title: string;
  imageUrl: string;
  price: string;
  priceAmount: number;
  available: boolean;
  affiliateUrl: string;
}

// Build lookup by ASIN for fast enrichment
const _apiProductsByAsin = new Map<string, AmazonProductEntry>();
if (amazonProductsData?.products && Array.isArray(amazonProductsData.products)) {
  for (const p of amazonProductsData.products as AmazonProductEntry[]) {
    if (p.asin) _apiProductsByAsin.set(p.asin, p);
  }
}

export interface CreatorProduct {
  id: string;
  asin: string;
  title: string;
  category: string;
  emoji: string;
  keywordTags: string[];
  payoutPriority: number; // 1-10 (higher = higher expected payout)
  searchQuery: string;
}

const DEFAULT_AMAZON_PARTNER_TAG = 'luigi066-21';

const MARKETPLACE_BY_LOCALE: Record<Locale, string> = {
  it: 'https://www.amazon.it',
  en: 'https://www.amazon.it',
  de: 'https://www.amazon.it',
  fr: 'https://www.amazon.it',
};

const CREATOR_PRODUCTS: CreatorProduct[] = [
  // ── Fisco & Finanza (6 prodotti) ──────────────────────────────
  {
    id: 'trading-book',
    asin: '8820383550',
    title: 'Investimenti e finanza personale (libro)',
    category: 'finance',
    emoji: '📈',
    keywordTags: ['cambio', 'chf', 'eur', 'investimenti', 'risparmio', 'borsa', 'frontalieri'],
    payoutPriority: 9,
    searchQuery: 'investimenti finanza personale libro',
  },
  {
    id: 'tax-guide-book',
    asin: '8891657401',
    title: 'Guida fiscale pratica (libro)',
    category: 'tax',
    emoji: '🧾',
    keywordTags: ['tasse', 'irpef', 'credito', 'imposta', 'dichiarazione', '730', 'frontaliere'],
    payoutPriority: 8,
    searchQuery: 'guida fiscale dichiarazione redditi 730 libro',
  },
  {
    id: 'tax-software',
    asin: 'B0BGQ7KHYH',
    title: 'Organizzazione documenti fiscali',
    category: 'tax',
    emoji: '📂',
    keywordTags: ['fiscale', 'documenti', 'scadenze', 'dichiarazione', 'moduli'],
    payoutPriority: 8,
    searchQuery: 'software gestione documenti fiscali',
  },
  {
    id: 'financial-calculator',
    asin: 'B00004UFNR',
    title: 'Calcolatrice finanziaria HP 12C',
    category: 'finance',
    emoji: '🔢',
    keywordTags: ['calcolo', 'interessi', 'mutuo', 'investimenti', 'finanza', 'cambio'],
    payoutPriority: 7,
    searchQuery: 'calcolatrice finanziaria HP 12C',
  },
  {
    id: 'intl-tax-book',
    asin: '8891425065',
    title: 'Fiscalità internazionale (libro)',
    category: 'tax',
    emoji: '🌍',
    keywordTags: ['tasse', 'frontaliere', 'svizzera', 'italia', 'doppia imposizione', 'accordo'],
    payoutPriority: 9,
    searchQuery: 'fiscalità internazionale doppia imposizione libro',
  },
  {
    id: 'document-organizer',
    asin: 'B0BN2YRQJL',
    title: 'Organizer documenti a fisarmonica',
    category: 'tax',
    emoji: '🗃️',
    keywordTags: ['documenti', 'dichiarazione', 'fiscale', 'organizzazione', 'archivio'],
    payoutPriority: 6,
    searchQuery: 'organizer documenti fisarmonica cartella',
  },

  // ── Trasporto & Pendolarismo (6 prodotti) ─────────────────────
  {
    id: 'dashcam',
    asin: 'B0CF9YV5SL',
    title: 'Dashcam per pendolari',
    category: 'transport',
    emoji: '🚗',
    keywordTags: ['traffico', 'frontiera', 'auto', 'pendolare', 'viaggio', 'trasporto'],
    payoutPriority: 7,
    searchQuery: 'dashcam auto full hd',
  },
  {
    id: 'phone-mount',
    asin: 'B0CXKZ98QP',
    title: 'Supporto smartphone magnetico auto',
    category: 'transport',
    emoji: '📱',
    keywordTags: ['auto', 'navigazione', 'pendolare', 'frontiera', 'gps', 'trasporto'],
    payoutPriority: 6,
    searchQuery: 'supporto smartphone magnetico auto cruscotto',
  },
  {
    id: 'car-charger',
    asin: 'B0B6QFFTMR',
    title: 'Caricatore auto USB-C rapido',
    category: 'transport',
    emoji: '🔌',
    keywordTags: ['auto', 'pendolare', 'ricarica', 'viaggio', 'trasporto'],
    payoutPriority: 5,
    searchQuery: 'caricatore auto USB-C ricarica rapida',
  },
  {
    id: 'lumbar-cushion',
    asin: 'B01M0QFWFH',
    title: 'Cuscino lombare ergonomico auto',
    category: 'transport',
    emoji: '🪑',
    keywordTags: ['auto', 'pendolare', 'schiena', 'ergonomia', 'viaggio', 'comfort'],
    payoutPriority: 6,
    searchQuery: 'cuscino lombare supporto auto ergonomico',
  },
  {
    id: 'commuter-bag',
    asin: 'B08SBR4GRG',
    title: 'Borsa laptop da pendolare',
    category: 'transport',
    emoji: '💼',
    keywordTags: ['pendolare', 'lavoro', 'laptop', 'treno', 'viaggio', 'trasporto'],
    payoutPriority: 6,
    searchQuery: 'borsa laptop pendolare impermeabile',
  },
  {
    id: 'audiobook-sub',
    asin: 'B01M3TIVPW',
    title: 'Audible - audiolibri in viaggio',
    category: 'transport',
    emoji: '🎧',
    keywordTags: ['pendolare', 'viaggio', 'auto', 'treno', 'audiolibri', 'formazione'],
    payoutPriority: 8,
    searchQuery: 'audible abbonamento audiolibri',
  },

  // ── Lavoro & Carriera (6 prodotti) ────────────────────────────
  {
    id: 'language-course',
    asin: '8869875968',
    title: 'Corso tedesco/francese per lavoro (libro)',
    category: 'career',
    emoji: '🗣️',
    keywordTags: ['lavoro', 'colloquio', 'cv', 'career', 'job', 'tedesco', 'francese'],
    payoutPriority: 8,
    searchQuery: 'corso tedesco lavoro libro',
  },
  {
    id: 'swiss-interview-guide',
    asin: '3038810371',
    title: 'Guida colloqui di lavoro in Svizzera',
    category: 'career',
    emoji: '🤝',
    keywordTags: ['colloquio', 'lavoro', 'svizzera', 'cv', 'career', 'job', 'candidatura'],
    payoutPriority: 8,
    searchQuery: 'guida colloquio lavoro svizzera preparazione',
  },
  {
    id: 'webcam-hd',
    asin: 'B09B8DWL3S',
    title: 'Webcam HD per smart working',
    category: 'career',
    emoji: '📹',
    keywordTags: ['smart working', 'lavoro', 'remoto', 'videocall', 'ufficio'],
    payoutPriority: 7,
    searchQuery: 'webcam full hd smart working',
  },
  {
    id: 'noise-cancelling-headphones',
    asin: 'B0C8PSQWB4',
    title: 'Cuffie noise cancelling per ufficio',
    category: 'career',
    emoji: '🎧',
    keywordTags: ['lavoro', 'ufficio', 'concentrazione', 'smart working', 'cuffie', 'rumore'],
    payoutPriority: 8,
    searchQuery: 'cuffie noise cancelling bluetooth ufficio',
  },
  {
    id: 'standing-desk-converter',
    asin: 'B08CKGH98Z',
    title: 'Standing desk converter regolabile',
    category: 'career',
    emoji: '🖥️',
    keywordTags: ['ergonomia', 'ufficio', 'smart working', 'salute', 'scrivania', 'lavoro'],
    payoutPriority: 7,
    searchQuery: 'standing desk converter scrivania regolabile',
  },
  {
    id: 'home-office-kit',
    asin: 'B0CKN3TNM3',
    title: 'Supporto laptop + ergonomia home office',
    category: 'productivity',
    emoji: '💻',
    keywordTags: ['smart working', 'lavoro', 'ufficio', 'casa', 'produttività'],
    payoutPriority: 7,
    searchQuery: 'kit ergonomia home office',
  },

  // ── Casa & Risparmio (5 prodotti) ─────────────────────────────
  {
    id: 'budget-planner',
    asin: 'B0B9S4Y4RN',
    title: 'Planner budget annuale',
    category: 'budget',
    emoji: '📒',
    keywordTags: ['budget', 'risparmio', 'stipendio', 'spese', 'franchi', 'euro'],
    payoutPriority: 7,
    searchQuery: 'planner budget mensile agenda',
  },
  {
    id: 'saving-book',
    asin: '8804734019',
    title: 'Libro sul risparmio e gestione denaro',
    category: 'budget',
    emoji: '💰',
    keywordTags: ['risparmio', 'budget', 'denaro', 'spese', 'stipendio', 'finanza'],
    payoutPriority: 7,
    searchQuery: 'libro risparmio gestione denaro personale',
  },
  {
    id: 'power-bank',
    asin: 'B0BVD1B58J',
    title: 'Power bank 20000mAh USB-C',
    category: 'travel',
    emoji: '🔋',
    keywordTags: ['viaggio', 'pendolare', 'ricarica', 'smartphone', 'lavoro'],
    payoutPriority: 5,
    searchQuery: 'power bank 20000mah usb-c ricarica rapida',
  },
  {
    id: 'thermos-coffee',
    asin: 'B07FDFSK1Q',
    title: 'Thermos caffè da viaggio 500ml',
    category: 'travel',
    emoji: '☕',
    keywordTags: ['pendolare', 'viaggio', 'caffè', 'mattina', 'auto', 'treno'],
    payoutPriority: 5,
    searchQuery: 'thermos caffè viaggio acciaio inox',
  },
  {
    id: 'travel-backpack',
    asin: 'B09YVCSLSN',
    title: 'Zaino business viaggio',
    category: 'travel',
    emoji: '🎒',
    keywordTags: ['trasporto', 'lavoro', 'frontalieri', 'viaggio', 'treno'],
    payoutPriority: 6,
    searchQuery: 'zaino business laptop viaggio',
  },

  // ── Salute & Benessere (4 prodotti) ───────────────────────────
  {
    id: 'health-guide-ch',
    asin: '3038811622',
    title: 'Guida sistema sanitario svizzero',
    category: 'health',
    emoji: '🏥',
    keywordTags: ['salute', 'assicurazione', 'lamal', 'cassa malati', 'svizzera', 'sanità'],
    payoutPriority: 8,
    searchQuery: 'guida sistema sanitario svizzero assicurazione',
  },
  {
    id: 'vitamins-commuter',
    asin: 'B071V2F8WS',
    title: 'Multivitaminico per ritmi intensi',
    category: 'health',
    emoji: '💊',
    keywordTags: ['salute', 'energia', 'stanchezza', 'pendolare', 'vitamine'],
    payoutPriority: 5,
    searchQuery: 'multivitaminico energia stanchezza integratore',
  },
  {
    id: 'water-bottle-thermal',
    asin: 'B07D5HKRXS',
    title: 'Borraccia termica 750ml',
    category: 'health',
    emoji: '🥤',
    keywordTags: ['salute', 'idratazione', 'viaggio', 'pendolare', 'borraccia'],
    payoutPriority: 4,
    searchQuery: 'borraccia termica acciaio inox 750ml',
  },
  {
    id: 'first-aid-kit-car',
    asin: 'B0716G63BQ',
    title: 'Kit primo soccorso auto',
    category: 'health',
    emoji: '🩹',
    keywordTags: ['auto', 'sicurezza', 'emergenza', 'pendolare', 'viaggio', 'primo soccorso'],
    payoutPriority: 5,
    searchQuery: 'kit primo soccorso auto emergenza',
  },
];


function buildAmazonAffiliateUrl(asin: string, locale: Locale, partnerTag: string): string {
  const marketplace = MARKETPLACE_BY_LOCALE[locale] || MARKETPLACE_BY_LOCALE.it;
  return `${marketplace}/dp/${asin}?tag=${encodeURIComponent(partnerTag)}&linkCode=ll1`;
}

function buildAmazonSearchAffiliateUrl(query: string, locale: Locale, partnerTag: string): string {
  const marketplace = MARKETPLACE_BY_LOCALE[locale] || MARKETPLACE_BY_LOCALE.it;
  const q = query.trim() || 'frontalieri svizzera italia';
  return `${marketplace}/s?k=${encodeURIComponent(q)}&tag=${encodeURIComponent(partnerTag)}&linkCode=ll2`;
}

function buildAmazonImageUrl(asin: string): string {
  const safeAsin = asin.trim();
  // Amazon Associates image widget — publicly accessible, no API required.
  // Returns 302 redirect to actual product image. _SL250_ for Retina sharpness.
  return `https://ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=${encodeURIComponent(safeAsin)}&Format=_SL250_&ID=AsinImage&MarketPlace=IT&ServiceVersion=20070822&WS=1&tag=luigi066-21`;
}

function isValidAmazonAffiliateUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    const host = parsed.hostname.toLowerCase();
    const validHost = host.endsWith('amazon.it') || host.endsWith('amazon.fr');
    const hasTag = Boolean(parsed.searchParams.get('tag'));
    const isSearch = parsed.pathname === '/s' && Boolean(parsed.searchParams.get('k'));
    const isDp = /\/dp\/[A-Z0-9]{8,12}/i.test(parsed.pathname);
    return validHost && hasTag && (isSearch || isDp);
  } catch {
    return false;
  }
}

export interface CreatorProductSuggestion extends CreatorProduct {
  score: number;
  url: string;
  partnerTag: string;
  query: string;
  imageUrl: string;
  keywordHits: number;
  /** FRO-336: Display price from Creators API (e.g. "€12,99") */
  price: string;
  /** FRO-336: Whether the product is currently available on Amazon */
  available: boolean;
}

interface CreatorProductInput {
  contextText: string;
  maxCards?: number;
}

// ── Session-based rotation seed ───────────────────────────────
const SESSION_SEED_KEY = 'amz_rotation_seed';

function getSessionSeed(): number {
  if (typeof window === 'undefined' || !window.sessionStorage) {
    return Math.random() * 0xFFFFFFFF >>> 0;
  }
  const stored = sessionStorage.getItem(SESSION_SEED_KEY);
  if (stored) {
    const parsed = parseInt(stored, 10);
    if (!isNaN(parsed)) return parsed;
  }
  const seed = Math.random() * 0xFFFFFFFF >>> 0;
  try {
    sessionStorage.setItem(SESSION_SEED_KEY, String(seed));
  } catch {
    // sessionStorage full or disabled — use ephemeral seed
  }
  return seed;
}

/** Simple deterministic hash combining seed + context for stable per-session rotation */
function rotationHash(seed: number, context: string): number {
  let h = seed;
  for (let i = 0; i < context.length; i += 1) {
    h = ((h << 5) - h + context.charCodeAt(i)) | 0;
  }
  return Math.abs(h);
}

export function getCreatorProductsForContext({
  contextText,
  maxCards = 2,
}: CreatorProductInput): CreatorProductSuggestion[] {
  const locale = getLocale();
  const normalized = contextText.toLowerCase();
  const partnerTag = DEFAULT_AMAZON_PARTNER_TAG;

  const scored = CREATOR_PRODUCTS.map((product) => {
    const keywordHits = product.keywordTags.reduce((acc, tag) => (normalized.includes(tag) ? acc + 1 : acc), 0);
    const score = keywordHits * 100 + product.payoutPriority * 3;
    const contextualQuery =
      keywordHits > 0
        ? `${product.searchQuery} ${product.keywordTags.filter((tag) => normalized.includes(tag)).slice(0, 2).join(' ')}`
        : product.searchQuery;
    const searchUrl = buildAmazonSearchAffiliateUrl(contextualQuery, locale, partnerTag);
    const fallbackDpUrl = buildAmazonAffiliateUrl(product.asin, locale, partnerTag);
    const url = isValidAmazonAffiliateUrl(searchUrl) ? searchUrl : fallbackDpUrl;
    // FRO-336: Enrich with real data from Creators API if available
    const apiData = _apiProductsByAsin.get(product.asin);
    // Only use the direct DP URL from API when we have confirmed real product data
    // (non-empty title). In fallback mode titles are empty and DP URLs may point to
    // products that don't exist on Amazon.it — prefer the contextual search URL.
    const hasRealApiData = Boolean(apiData?.title && apiData.title.trim() !== '');
    return {
      ...product,
      score,
      url: hasRealApiData ? (apiData!.affiliateUrl || url) : url,
      partnerTag,
      query: contextualQuery.trim(),
      imageUrl: apiData?.imageUrl || buildAmazonImageUrl(product.asin),
      keywordHits,
      price: apiData?.price || '',
      available: apiData?.available ?? true,
    };
  });

  const maxHits = scored.reduce((m, p) => Math.max(m, p.keywordHits), 0);
  const pool = maxHits > 0 ? scored.filter((p) => p.keywordHits > 0) : scored;

  const sorted = pool.sort((a, b) => b.score - a.score);
  const pickCount = Math.max(1, Math.min(maxCards, sorted.length));
  const rotationPoolSize = Math.min(sorted.length, Math.max(pickCount * 3, 6));
  const rotationPool = sorted.slice(0, rotationPoolSize);

  // Per-session rotation: each browser session gets a unique seed
  const sessionSeed = getSessionSeed();
  const rotationStart = rotationHash(sessionSeed, `${locale}|${normalized}`) % rotationPool.length;
  const ranked: CreatorProductSuggestion[] = [];
  for (let i = 0; i < pickCount; i += 1) {
    ranked.push(rotationPool[(rotationStart + i) % rotationPool.length]);
  }

  return ranked;
}
