import { getLocale, type Locale } from '@/services/i18n';

// FRO-336: Import build-time Amazon product data (generated by fetch-amazon-products.mjs)
import amazonProductsData from '@/data/amazon-products.json';

interface AmazonProductEntry {
  asin: string;
  title: string;
  imageUrl: string;
  price: string;
  priceAmount: number;
  available: boolean;
  affiliateUrl: string;
}

// Build lookup by ASIN for fast enrichment
const _apiProductsByAsin = new Map<string, AmazonProductEntry>();
if (amazonProductsData?.products && Array.isArray(amazonProductsData.products)) {
  for (const p of amazonProductsData.products as AmazonProductEntry[]) {
    if (p.asin) _apiProductsByAsin.set(p.asin, p);
  }
}

export interface CreatorProduct {
  id: string;
  asin: string;
  title: string;
  category: string;
  emoji: string;
  /** Amazon CDN image ID (from m.media-amazon.com/images/I/{imageId}) */
  imageId: string;
  keywordTags: string[];
  payoutPriority: number; // 1-10 (higher = higher expected payout)
  searchQuery: string;
}

const DEFAULT_AMAZON_PARTNER_TAG = 'luigi066-21';

const MARKETPLACE_BY_LOCALE: Record<Locale, string> = {
  it: 'https://www.amazon.it',
  en: 'https://www.amazon.it',
  de: 'https://www.amazon.it',
  fr: 'https://www.amazon.it',
};

const CREATOR_PRODUCTS: CreatorProduct[] = [
  // ── Fisco & Finanza (6 prodotti) ──────────────────────────────
  {
    id: 'trading-book',
    asin: '8820396246',
    title: "L'investitore intelligente (libro)",
    category: 'finance',
    emoji: '📈',
    imageId: '61T4a87qvXL',
    keywordTags: ['cambio', 'chf', 'eur', 'investimenti', 'risparmio', 'borsa', 'frontalieri'],
    payoutPriority: 9,
    searchQuery: 'investimenti finanza personale libro',
  },
  {
    id: 'tax-guide-book',
    asin: 'B0F7DS11QM',
    title: 'Guida dichiarazione dei redditi (libro)',
    category: 'tax',
    emoji: '🧾',
    imageId: '71EXhOHXu8L',
    keywordTags: ['tasse', 'irpef', 'credito', 'imposta', 'dichiarazione', '730', 'frontaliere'],
    payoutPriority: 8,
    searchQuery: 'guida fiscale dichiarazione redditi libro',
  },
  {
    id: 'tax-software',
    asin: 'B0DMVCCQVR',
    title: 'Cartellina portadocumenti A4',
    category: 'tax',
    emoji: '📂',
    imageId: '51mDwIbT31L',
    keywordTags: ['fiscale', 'documenti', 'scadenze', 'dichiarazione', 'moduli'],
    payoutPriority: 8,
    searchQuery: 'cartella organizzazione documenti fiscali',
  },
  {
    id: 'financial-calculator',
    asin: 'B005D7H39G',
    title: 'Calcolatrice finanziaria HP 12C',
    category: 'finance',
    emoji: '🔢',
    imageId: '61Mhyvb0TfL',
    keywordTags: ['calcolo', 'interessi', 'mutuo', 'investimenti', 'finanza', 'cambio'],
    payoutPriority: 7,
    searchQuery: 'calcolatrice finanziaria HP 12C',
  },
  {
    id: 'intl-tax-book',
    asin: 'B0GPRG8139',
    title: 'Diritto tributario internazionale (libro)',
    category: 'tax',
    emoji: '🌍',
    imageId: '61XBQ8fh7VL',
    keywordTags: ['tasse', 'frontaliere', 'svizzera', 'italia', 'doppia imposizione', 'accordo'],
    payoutPriority: 9,
    searchQuery: 'fiscalità internazionale doppia imposizione libro',
  },
  {
    id: 'document-organizer',
    asin: 'B07RQWZY34',
    title: 'Cartella portadocumenti espandibile A4',
    category: 'tax',
    emoji: '🗃️',
    imageId: '61pwfbAqa4L',
    keywordTags: ['documenti', 'dichiarazione', 'fiscale', 'organizzazione', 'archivio'],
    payoutPriority: 6,
    searchQuery: 'organizer documenti fisarmonica cartella',
  },

  // ── Trasporto & Pendolarismo (6 prodotti) ─────────────────────
  {
    id: 'dashcam',
    asin: 'B0CVXDGNWP',
    title: 'Dashcam auto 4K con GPS e WiFi',
    category: 'transport',
    emoji: '🚗',
    imageId: '71hjyQv4u3L',
    keywordTags: ['traffico', 'frontiera', 'auto', 'pendolare', 'viaggio', 'trasporto'],
    payoutPriority: 7,
    searchQuery: 'dashcam auto full hd',
  },
  {
    id: 'phone-mount',
    asin: 'B0FMRG6J3T',
    title: 'Supporto smartphone magnetico MagSafe auto',
    category: 'transport',
    emoji: '📱',
    imageId: '81xjrTmX5SL',
    keywordTags: ['auto', 'navigazione', 'pendolare', 'frontiera', 'gps', 'trasporto'],
    payoutPriority: 6,
    searchQuery: 'supporto smartphone magnetico auto cruscotto',
  },
  {
    id: 'car-charger',
    asin: 'B0F21QKF44',
    title: 'Caricatore auto USB-C 50W rapido',
    category: 'transport',
    emoji: '🔌',
    imageId: '613hCCJGB3L',
    keywordTags: ['auto', 'pendolare', 'ricarica', 'viaggio', 'trasporto'],
    payoutPriority: 5,
    searchQuery: 'caricatore auto USB-C ricarica rapida',
  },
  {
    id: 'lumbar-cushion',
    asin: 'B096RRKV2Y',
    title: 'Cuscino lombare ergonomico memory foam',
    category: 'transport',
    emoji: '🪑',
    imageId: '71OqETd1iDL',
    keywordTags: ['auto', 'pendolare', 'schiena', 'ergonomia', 'viaggio', 'comfort'],
    payoutPriority: 6,
    searchQuery: 'cuscino lombare supporto auto ergonomico',
  },
  {
    id: 'commuter-bag',
    asin: 'B0FF4X2JB9',
    title: 'Zaino laptop da pendolare',
    category: 'transport',
    emoji: '💼',
    imageId: '61n+148j0uL',
    keywordTags: ['pendolare', 'lavoro', 'laptop', 'treno', 'viaggio', 'trasporto'],
    payoutPriority: 6,
    searchQuery: 'borsa laptop pendolare impermeabile',
  },
  {
    id: 'audiobook-sub',
    asin: 'B01BNITJOU',
    title: 'Audible - audiolibri in viaggio',
    category: 'transport',
    emoji: '🎧',
    imageId: '21MjMFj7JAL',
    keywordTags: ['pendolare', 'viaggio', 'auto', 'treno', 'audiolibri', 'formazione'],
    payoutPriority: 8,
    searchQuery: 'audible abbonamento audiolibri',
  },

  // ── Lavoro & Carriera (6 prodotti) ────────────────────────────
  {
    id: 'language-course',
    asin: '8858345258',
    title: 'Grammatica tedesca con esercizi (libro)',
    category: 'career',
    emoji: '🗣️',
    imageId: '51R75cc+GuL',
    keywordTags: ['lavoro', 'colloquio', 'cv', 'career', 'job', 'tedesco', 'francese'],
    payoutPriority: 8,
    searchQuery: 'corso tedesco lavoro libro',
  },
  {
    id: 'swiss-interview-guide',
    asin: 'B0C5BCCCVG',
    title: 'Guida colloquio di lavoro vincente (libro)',
    category: 'career',
    emoji: '🤝',
    imageId: '71PsXIVtmXL',
    keywordTags: ['colloquio', 'lavoro', 'svizzera', 'cv', 'career', 'job', 'candidatura'],
    payoutPriority: 8,
    searchQuery: 'guida colloquio lavoro svizzera preparazione',
  },
  {
    id: 'webcam-hd',
    asin: 'B09ZKXV1MY',
    title: 'Webcam 1080P con microfono e altoparlante',
    category: 'career',
    emoji: '📹',
    imageId: '610JhJ3RWuL',
    keywordTags: ['smart working', 'lavoro', 'remoto', 'videocall', 'ufficio'],
    payoutPriority: 7,
    searchQuery: 'webcam full hd smart working',
  },
  {
    id: 'noise-cancelling-headphones',
    asin: 'B0F12Q56RZ',
    title: 'Cuffie noise cancelling wireless',
    category: 'career',
    emoji: '🎧',
    imageId: '71n1M3fhlJL',
    keywordTags: ['lavoro', 'ufficio', 'concentrazione', 'smart working', 'cuffie', 'rumore'],
    payoutPriority: 8,
    searchQuery: 'cuffie noise cancelling bluetooth ufficio',
  },
  {
    id: 'standing-desk-converter',
    asin: 'B08PV7XY8M',
    title: 'Standing desk converter regolabile',
    category: 'career',
    emoji: '🖥️',
    imageId: '616MA59OzuL',
    keywordTags: ['ergonomia', 'ufficio', 'smart working', 'salute', 'scrivania', 'lavoro'],
    payoutPriority: 7,
    searchQuery: 'standing desk converter scrivania regolabile',
  },
  {
    id: 'home-office-kit',
    asin: 'B0CCNQP9F2',
    title: 'Supporto laptop ergonomico pieghevole',
    category: 'productivity',
    emoji: '💻',
    imageId: '61lKZJiIyVL',
    keywordTags: ['smart working', 'lavoro', 'ufficio', 'casa', 'produttività'],
    payoutPriority: 7,
    searchQuery: 'supporto laptop ergonomia home office',
  },

  // ── Casa & Risparmio (5 prodotti) ─────────────────────────────
  {
    id: 'budget-planner',
    asin: 'B072QR1S3T',
    title: 'Lavagna calendario magnetico per budget',
    category: 'budget',
    emoji: '📒',
    imageId: '71Y2r1pgBkL',
    keywordTags: ['budget', 'risparmio', 'stipendio', 'spese', 'franchi', 'euro'],
    payoutPriority: 7,
    searchQuery: 'planner budget mensile agenda',
  },
  {
    id: 'saving-book',
    asin: 'B0GG3RXDML',
    title: 'Il libro del risparmio e budget planner',
    category: 'budget',
    emoji: '💰',
    imageId: '71KneLITCuL',
    keywordTags: ['risparmio', 'budget', 'denaro', 'spese', 'stipendio', 'finanza'],
    payoutPriority: 7,
    searchQuery: 'libro risparmio gestione denaro personale',
  },
  {
    id: 'power-bank',
    asin: 'B0D8KH4LNB',
    title: 'Power bank 20000mAh 45W USB-C',
    category: 'travel',
    emoji: '🔋',
    imageId: '51IqMiHCMQL',
    keywordTags: ['viaggio', 'pendolare', 'ricarica', 'smartphone', 'lavoro'],
    payoutPriority: 5,
    searchQuery: 'power bank 20000mah usb-c ricarica rapida',
  },
  {
    id: 'thermos-coffee',
    asin: 'B0CH4WGRQQ',
    title: 'Thermos caffè da viaggio acciaio inox',
    category: 'travel',
    emoji: '☕',
    imageId: '61MFmJpKvuL',
    keywordTags: ['pendolare', 'viaggio', 'caffè', 'mattina', 'auto', 'treno'],
    payoutPriority: 5,
    searchQuery: 'thermos caffè viaggio acciaio inox',
  },
  {
    id: 'travel-backpack',
    asin: 'B0DFC7Q2GK',
    title: 'Zaino business da viaggio',
    category: 'travel',
    emoji: '🎒',
    imageId: '71dbom9FTrL',
    keywordTags: ['trasporto', 'lavoro', 'frontalieri', 'viaggio', 'treno'],
    payoutPriority: 6,
    searchQuery: 'zaino business laptop viaggio',
  },

  // ── Salute & Benessere (4 prodotti) ───────────────────────────
  {
    id: 'health-guide-ch',
    asin: 'B0F6NDGT7W',
    title: 'Assicurazione malattia: le regole del gioco',
    category: 'health',
    emoji: '🏥',
    imageId: '61FwkENkulL',
    keywordTags: ['salute', 'assicurazione', 'lamal', 'cassa malati', 'svizzera', 'sanità'],
    payoutPriority: 8,
    searchQuery: 'assicurazione sanitaria svizzera guida libro',
  },
  {
    id: 'vitamins-commuter',
    asin: 'B0CKF3PGDV',
    title: 'Be-Total Advance B12 integratore',
    category: 'health',
    emoji: '💊',
    imageId: '61NaavrxwVL',
    keywordTags: ['salute', 'energia', 'stanchezza', 'pendolare', 'vitamine'],
    payoutPriority: 5,
    searchQuery: 'multivitaminico energia stanchezza integratore',
  },
  {
    id: 'water-bottle-thermal',
    asin: 'B0GF1RX5RK',
    title: 'Borraccia termica 750ml acciaio inox',
    category: 'health',
    emoji: '🥤',
    imageId: '615TKlZZ4hL',
    keywordTags: ['salute', 'idratazione', 'viaggio', 'pendolare', 'borraccia'],
    payoutPriority: 4,
    searchQuery: 'borraccia termica acciaio inox 750ml',
  },
  {
    id: 'first-aid-kit-car',
    asin: 'B07FRPXF44',
    title: 'Kit primo soccorso auto premium',
    category: 'health',
    emoji: '🩹',
    imageId: '61mSrFlJh8L',
    keywordTags: ['auto', 'sicurezza', 'emergenza', 'pendolare', 'viaggio', 'primo soccorso'],
    payoutPriority: 5,
    searchQuery: 'kit primo soccorso auto emergenza',
  },
];


function buildAmazonAffiliateUrl(asin: string, locale: Locale, partnerTag: string): string {
  const marketplace = MARKETPLACE_BY_LOCALE[locale] || MARKETPLACE_BY_LOCALE.it;
  return `${marketplace}/dp/${asin}?tag=${encodeURIComponent(partnerTag)}&linkCode=ll1`;
}

function buildAmazonSearchAffiliateUrl(query: string, locale: Locale, partnerTag: string): string {
  const marketplace = MARKETPLACE_BY_LOCALE[locale] || MARKETPLACE_BY_LOCALE.it;
  const q = query.trim() || 'frontalieri svizzera italia';
  return `${marketplace}/s?k=${encodeURIComponent(q)}&tag=${encodeURIComponent(partnerTag)}&linkCode=ll2`;
}

/** Build a reliable Amazon CDN image URL from the product's imageId.
 *  Uses m.media-amazon.com/images/I/ which is the same CDN Amazon uses
 *  for search results — stable, fast, no auth required.
 *  _AC_UL320_ = auto-crop, uniform length 320px (sharp at 72px display = 4x). */
function buildAmazonImageUrl(imageId: string): string {
  if (!imageId) return '';
  return `https://m.media-amazon.com/images/I/${imageId}._AC_UL320_.jpg`;
}

function isValidAmazonAffiliateUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    const host = parsed.hostname.toLowerCase();
    const validHost = host.endsWith('amazon.it') || host.endsWith('amazon.fr');
    const hasTag = Boolean(parsed.searchParams.get('tag'));
    const isSearch = parsed.pathname === '/s' && Boolean(parsed.searchParams.get('k'));
    const isDp = /\/dp\/[A-Z0-9]{8,12}/i.test(parsed.pathname);
    return validHost && hasTag && (isSearch || isDp);
  } catch {
    return false;
  }
}

export interface CreatorProductSuggestion extends CreatorProduct {
  score: number;
  url: string;
  partnerTag: string;
  query: string;
  imageUrl: string;
  keywordHits: number;
  /** FRO-336: Display price from Creators API (e.g. "€12,99") */
  price: string;
  /** FRO-336: Whether the product is currently available on Amazon */
  available: boolean;
}

interface CreatorProductInput {
  contextText: string;
  maxCards?: number;
}

// ── Session-based rotation seed ───────────────────────────────
const SESSION_SEED_KEY = 'amz_rotation_seed';

function getSessionSeed(): number {
  if (typeof window === 'undefined' || !window.sessionStorage) {
    return Math.random() * 0xFFFFFFFF >>> 0;
  }
  const stored = sessionStorage.getItem(SESSION_SEED_KEY);
  if (stored) {
    const parsed = parseInt(stored, 10);
    if (!isNaN(parsed)) return parsed;
  }
  const seed = Math.random() * 0xFFFFFFFF >>> 0;
  try {
    sessionStorage.setItem(SESSION_SEED_KEY, String(seed));
  } catch {
    // sessionStorage full or disabled — use ephemeral seed
  }
  return seed;
}

/** Simple deterministic hash combining seed + context for stable per-session rotation */
function rotationHash(seed: number, context: string): number {
  let h = seed;
  for (let i = 0; i < context.length; i += 1) {
    h = ((h << 5) - h + context.charCodeAt(i)) | 0;
  }
  return Math.abs(h);
}

export function getCreatorProductsForContext({
  contextText,
  maxCards = 2,
}: CreatorProductInput): CreatorProductSuggestion[] {
  const locale = getLocale();
  const normalized = contextText.toLowerCase();
  const partnerTag = DEFAULT_AMAZON_PARTNER_TAG;

  const scored = CREATOR_PRODUCTS.map((product) => {
    const keywordHits = product.keywordTags.reduce((acc, tag) => (normalized.includes(tag) ? acc + 1 : acc), 0);
    const score = keywordHits * 100 + product.payoutPriority * 3;
    const contextualQuery =
      keywordHits > 0
        ? `${product.searchQuery} ${product.keywordTags.filter((tag) => normalized.includes(tag)).slice(0, 2).join(' ')}`
        : product.searchQuery;
    const searchUrl = buildAmazonSearchAffiliateUrl(contextualQuery, locale, partnerTag);
    const fallbackDpUrl = buildAmazonAffiliateUrl(product.asin, locale, partnerTag);
    const url = isValidAmazonAffiliateUrl(searchUrl) ? searchUrl : fallbackDpUrl;
    // FRO-336: Enrich with real data from Creators API if available
    const apiData = _apiProductsByAsin.get(product.asin);
    // Only use the direct DP URL from API when we have confirmed real product data
    // (non-empty title). In fallback mode the JSON has empty titles and the DP URLs
    // may point to products that don't exist on Amazon.it — prefer the search URL.
    const hasRealApiData = Boolean(apiData?.title && apiData.title.trim() !== '');
    return {
      ...product,
      score,
      url: hasRealApiData ? (apiData!.affiliateUrl || url) : url,
      partnerTag,
      query: contextualQuery.trim(),
      imageUrl: apiData?.imageUrl || buildAmazonImageUrl(product.imageId),
      keywordHits,
      price: apiData?.price || '',
      available: apiData?.available ?? true,
    };
  });

  const maxHits = scored.reduce((m, p) => Math.max(m, p.keywordHits), 0);
  const pool = maxHits > 0 ? scored.filter((p) => p.keywordHits > 0) : scored;

  const sorted = pool.sort((a, b) => b.score - a.score);
  const pickCount = Math.max(1, Math.min(maxCards, sorted.length));
  const rotationPoolSize = Math.min(sorted.length, Math.max(pickCount * 3, 6));
  const rotationPool = sorted.slice(0, rotationPoolSize);

  // Per-session rotation: each browser session gets a unique seed
  const sessionSeed = getSessionSeed();
  const rotationStart = rotationHash(sessionSeed, `${locale}|${normalized}`) % rotationPool.length;
  const ranked: CreatorProductSuggestion[] = [];
  for (let i = 0; i < pickCount; i += 1) {
    ranked.push(rotationPool[(rotationStart + i) % rotationPool.length]);
  }

  return ranked;
}
