/**
 * Runtime resolution of article URLs the bundle has never heard of.
 *
 * `packages/articles/content/blogArticleIds.ts` and `routerBlogData.ts` are
 * COMPILED INTO THIS BUNDLE. An article generated by
 * nanakokyobashi-rgb/frontaliere-articles after the last successful deploy is
 * live at its own URL within a minute — the shard serves a complete, correct
 * static page — but its id is in neither file. `resolveBlogSlug()` returns
 * `undefined`, `blogArticle` stays null, and the SPA renders the blog LIST over
 * a perfectly good article page. Measured 2026-08-04 on
 * /articoli-frontaliere/poste-italiane-consulenti-finanziari-varese/: the h1
 * goes from "Poste Italiane cerca consulenti finanziari in Varese" before
 * hydration to "Guida Frontaliere" after it. Seventeen pages were in that state
 * (8 frontaliere + 9 svizzera); the count grows with every publish and only
 * resets on a successful deploy, which takes ~1.5h here and is often cancelled.
 *
 * This module teaches the running SPA the ids it was not built with, from the
 * JSON the corpus already publishes. It never replaces the bundled maps — it is
 * consulted only after they have been loaded and have come up empty.
 *
 * FAIL-OPEN IS THE WHOLE POINT. Every entry point resolves to `null` on a
 * missing file, a bad status, malformed JSON, a shape that does not match, a
 * timeout or an offline network. `null` means "the caller must not take over
 * the page", and the caller's answer to that is to leave the shard's static
 * HTML on screen — which is correct and complete. A page must never come out of
 * this worse than it went in.
 */

import { cdnDataUrl } from '@/services/cdnDataBase';
import { fetchArticleOverlay, type OverlayArticle, type OverlaySection } from '@/services/articlesOverlay';
import { mergeArticleMetaOverlay } from '@/services/i18n';
import type { Locale } from '@/services/i18n';
import { staticArticleFallback } from '@/services/staticArticleFallback';

export type { OverlaySection };

/** Beyond this a fetch is abandoned. Nothing here may hold a page hostage. */
const TIMEOUT_MS = 6000;

const ARTICLE_LOCALES: readonly Locale[] = ['it', 'en', 'de', 'fr'];

declare global {
  interface Window {
    /** Overrides the corpus API origin — set by tests and by the local dev server. */
    __ARTICLES_API_BASE__?: string;
  }
}

/**
 * Where the corpus publishes its JSON. Same default as
 * `scripts/lib/articles-api-base.mjs`, which every node-side reader imports,
 * so the site and its build scripts read one origin. The literal is repeated
 * here rather than imported because that module resolves `process.env`, which
 * does not exist in a browser — this copy is the client-side fallback for when
 * nothing injected `__ARTICLES_API_BASE__`, not a second source of truth.
 * The contract is JSON documents, never ES modules — see the
 * "Perché JSON e non un modulo" section of the frontaliere-articles README and
 * issue #4974: the previous module-shaped coupling silently changed export
 * shape between build tools and stranded every article page on a skeleton.
 */
export function articlesApiBase(): string {
  if (typeof window !== 'undefined') {
    const injected = window.__ARTICLES_API_BASE__;
    if (typeof injected === 'string' && injected) return injected.replace(/\/$/, '');
  }
  return 'https://nanakokyobashi-rgb.github.io/frontaliere-articles';
}

async function fetchJson(url: string): Promise<unknown | null> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(url, { signal: controller.signal });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

// ── slugs.json ──────────────────────────────────────────────────────────────

/** id → per-locale slug, for one section. */
type ForwardMap = Record<string, Partial<Record<Locale, string>>>;
/** locale → slug → id, for one section. */
type ReverseMap = Partial<Record<Locale, Record<string, string>>>;

interface SectionSlugMaps {
  forward: ForwardMap;
  reverse: ReverseMap;
}

export interface PublishedSlugMaps {
  frontaliere: SectionSlugMaps;
  svizzera: SectionSlugMaps;
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/**
 * Narrows one `{ id: { it, en, de, fr } }` half of slugs.json.
 *
 * Entries that do not match are dropped one by one rather than failing the
 * whole document: a single malformed record must not cost us the other 3,000.
 */
function readForward(raw: unknown): ForwardMap {
  if (!isRecord(raw)) return {};
  const out: ForwardMap = {};
  for (const [id, byLocale] of Object.entries(raw)) {
    if (!id || !isRecord(byLocale)) continue;
    const slugs: Partial<Record<Locale, string>> = {};
    for (const locale of ARTICLE_LOCALES) {
      const slug = byLocale[locale];
      if (typeof slug === 'string' && slug) slugs[locale] = slug;
    }
    if (Object.keys(slugs).length > 0) out[id] = slugs;
  }
  return out;
}

function readReverse(raw: unknown): ReverseMap {
  if (!isRecord(raw)) return {};
  const out: ReverseMap = {};
  for (const locale of ARTICLE_LOCALES) {
    const bySlug = raw[locale];
    if (!isRecord(bySlug)) continue;
    const table: Record<string, string> = {};
    for (const [slug, id] of Object.entries(bySlug)) {
      if (slug && typeof id === 'string' && id) table[slug] = id;
    }
    out[locale] = table;
  }
  return out;
}

let slugMapsPromise: Promise<PublishedSlugMaps | null> | null = null;

/**
 * The published id ↔ slug maps, fetched once per page load.
 *
 * ~550 KB gzipped for 3,700 articles across four locales, which is why this is
 * NOT on the common path: it is reached only when the bundled reverse map has
 * already failed to resolve the slug AND the cheap probe below has missed. A
 * visitor on an article the bundle knows never pays a byte of it.
 */
export function loadPublishedSlugMaps(): Promise<PublishedSlugMaps | null> {
  if (!slugMapsPromise) {
    slugMapsPromise = fetchJson(`${articlesApiBase()}/slugs.json`).then((raw) => {
      if (!isRecord(raw)) return null;
      const maps: PublishedSlugMaps = {
        frontaliere: { forward: readForward(raw.blog), reverse: readReverse(raw.blogReverse) },
        svizzera: { forward: readForward(raw.swiss), reverse: readReverse(raw.swissReverse) },
      };
      // A document that parses but carries no usable pair is indistinguishable
      // from a failure for our purposes, and saying so lets callers keep one
      // fail-open branch instead of two.
      const usable = Object.keys(maps.frontaliere.forward).length + Object.keys(maps.svizzera.forward).length;
      return usable > 0 ? maps : null;
    }).catch(() => null);
  }
  return slugMapsPromise;
}

/** Test seam — drops the cached slugs.json so the next call refetches. */
export function __resetRuntimeArticleResolution(): void {
  slugMapsPromise = null;
  runtimeRecords.frontaliere.clear();
  runtimeRecords.svizzera.clear();
}

// ── slug → id ───────────────────────────────────────────────────────────────

export interface ResolvedArticle {
  id: string;
  /** Every locale slug we could learn, so buildPath can emit canonical URLs. */
  slugs: Partial<Record<Locale, string>>;
  /** The published index entry, when the index carries it. */
  record: OverlayArticle | null;
}

/**
 * Resolve a URL slug the bundle does not know to its article id.
 *
 * Two tiers, cheapest first.
 *
 * TIER 1 — the published index the blog list already fetches. 2,909 of the
 * 3,085 frontaliere ids and all 615 svizzera ids ARE their own Italian slug
 * (measured 2026-08-05 against slugs.json), and the articles caught by this
 * defect are the newest ones, which sit inside the 150-entry recent window. So
 * "is this slug an id the index knows?" answers the common case from a 65 KB
 * file the page is fetching anyway — an HTTP cache hit in practice.
 *
 * The obvious objection to that shortcut is a slug that belongs to article A
 * while also being the id of a different article B. Across all 3,700 articles
 * and all four locales there are currently ZERO such pairs, and the tier is
 * gated on the id actually existing in the published index, so a stray URL
 * cannot invent one.
 *
 * TIER 2 — slugs.json's reverse map, which is authoritative and answers every
 * remaining case: renamed slugs, and the en/de/fr URLs where the slug is
 * localized and never equals the id.
 */
export async function resolveArticleBySlug(
  section: OverlaySection,
  locale: Locale,
  slug: string,
): Promise<ResolvedArticle | null> {
  if (!slug) return null;

  const indexed = await fetchArticleOverlay(section, locale).catch(() => [] as OverlayArticle[]);
  const byId = new Map(indexed.map((a) => [a.id, a]));

  // Tier 1.
  const direct = byId.get(slug);
  if (direct) {
    return { id: slug, slugs: { [locale]: slug }, record: direct };
  }

  // Tier 2.
  const maps = await loadPublishedSlugMaps();
  const id = maps?.[section].reverse[locale]?.[slug];
  if (!id) return null;
  return {
    id,
    slugs: maps?.[section].forward[id] ?? { [locale]: slug },
    record: byId.get(id) ?? null,
  };
}

// ── the records the SPA needs to render a runtime-resolved article ──────────

const runtimeRecords: Record<OverlaySection, Map<string, OverlayArticle>> = {
  frontaliere: new Map(),
  svizzera: new Map(),
};

/**
 * Index entries learned at runtime, for a list component to merge into its own
 * bundled registry. Without this the article view has an id it cannot look up:
 * `articleById.get(selectedArticle)` misses and BlogArticles renders nothing.
 */
export function runtimeArticleRecords(section: OverlaySection): OverlayArticle[] {
  return [...runtimeRecords[section].values()];
}

function rememberRecord(section: OverlaySection, record: OverlayArticle | null): void {
  if (record) runtimeRecords[section].set(record.id, record);
}

// ── body ────────────────────────────────────────────────────────────────────

/**
 * The corpus publishes titles, excerpts, slugs, sitemaps and feeds — but NOT
 * article bodies. Rather than invent an endpoint for them, the body is read
 * back from the static HTML the shard is already serving for that exact URL:
 * `ogPagesPlugin` renders it into `<main class="seo-static-content">
 * <article class="ft-blog-article">`, one `<section>` per bodyN part, and on an
 * article page that markup is in the DOM before React runs.
 *
 * The vocabulary is small and fixed (`renderArticleBodyHtml` in
 * packages/articles/engine/articleSeoFallback.ts emits only h2/h3/h4, p, ul>li,
 * blockquote and the inline set below), so the inverse is exact rather than a
 * general HTML-to-markdown guess. What it cannot recover is length: the static
 * renderer truncates each section at 1,800 rendered characters and marks the
 * cut with a "…" paragraph. That is the same text the visitor is already
 * reading, so a takeover built on it never removes content from the page — but
 * it is why this is a recovery path and not a replacement for a deploy.
 */
const INLINE_UNWRAP: Array<[string, (inner: string, el: Element) => string]> = [
  ['STRONG', (inner) => `**${inner}**`],
  ['B', (inner) => `**${inner}**`],
  ['EM', (inner) => `*${inner}*`],
  ['I', (inner) => `*${inner}*`],
  ['CODE', (inner) => `\`${inner}\``],
  ['A', (inner, el) => {
    const href = el.getAttribute('href');
    return href ? `[${inner}](${href})` : inner;
  }],
];

function inlineMarkdown(node: Node): string {
  if (node.nodeType === 3 /* TEXT_NODE */) return node.nodeValue ?? '';
  if (node.nodeType !== 1 /* ELEMENT_NODE */) return '';
  const el = node as Element;
  const inner = Array.from(el.childNodes).map(inlineMarkdown).join('');
  if (el.tagName === 'BR') return ' ';
  const rule = INLINE_UNWRAP.find(([tag]) => tag === el.tagName);
  return rule ? rule[1](inner, el) : inner;
}

/** A truncation marker is not content — carrying it over would be noise. */
const ELLIPSIS_ONLY = /^[…\s.]*$/;

function blockMarkdown(el: Element): string | null {
  const tag = el.tagName;
  if (tag === 'H2' || tag === 'H3' || tag === 'H4' || tag === 'H5' || tag === 'H6') {
    const level = tag === 'H2' ? '##' : tag === 'H3' ? '###' : '####';
    const text = inlineMarkdown(el).trim();
    return text ? `${level} ${text}` : null;
  }
  if (tag === 'P') {
    const text = inlineMarkdown(el).trim();
    return text && !ELLIPSIS_ONLY.test(text) ? text : null;
  }
  if (tag === 'UL' || tag === 'OL') {
    const items = Array.from(el.children)
      .filter((li) => li.tagName === 'LI')
      .map((li) => inlineMarkdown(li).trim())
      .filter(Boolean)
      .map((text) => `- ${text}`);
    return items.length ? items.join('\n') : null;
  }
  if (tag === 'BLOCKQUOTE') {
    const text = inlineMarkdown(el).trim();
    return text ? `> ${text}` : null;
  }
  return null;
}

/**
 * Body parts (one per `bodyN` key) recovered from a rendered article element.
 *
 * `article` is the `<article class="ft-blog-article">` node. Only its DIRECT
 * unclassed `<section>` children are body: the related-articles block and the
 * FAQ carry classes and are emitted separately by the plugin, and pulling them
 * in would duplicate content the SPA renders on its own.
 */
export function articleBodyPartsFromStaticArticle(article: Element | null): string[] {
  if (!article) return [];
  const sections = Array.from(article.children).filter(
    (el) => el.tagName === 'SECTION' && !el.getAttribute('class'),
  );
  const parts: string[] = [];
  for (const section of sections) {
    const blocks: string[] = [];
    for (const child of Array.from(section.children)) {
      const block = blockMarkdown(child);
      if (block) blocks.push(block);
    }
    const text = blocks.join('\n\n').trim();
    if (text) parts.push(text);
  }
  return parts;
}

/**
 * The static article element for the CURRENT page, when the shard served one.
 *
 * Goes through `staticArticleFallback` rather than the live DOM because by the
 * time we ask, the entry's CLS handoff has usually moved the static main inside
 * `#root` and React has replaced it. The clone taken before that move is the
 * only copy left.
 */
export function staticArticleElement(): Element | null {
  return staticArticleFallback()?.querySelector('article.ft-blog-article') ?? null;
}

/**
 * Same recovery for an article the visitor navigates to CLIENT-SIDE, where
 * there is no static HTML in the DOM: re-read the shard's own page. Same URL a
 * full navigation would have loaded, so this adds no endpoint and no contract.
 */
export async function fetchArticleBodyParts(path: string): Promise<string[]> {
  if (typeof DOMParser === 'undefined') return [];
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(path, { signal: controller.signal });
    if (!res.ok) return [];
    const html = await res.text();
    const doc = new DOMParser().parseFromString(html, 'text/html');
    return articleBodyPartsFromStaticArticle(
      doc.querySelector('main.seo-static-content article.ft-blog-article'),
    );
  } catch {
    return [];
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Publish a recovered body under the same `blog.article.<id>.bodyN` keys the
 * bundled chunks use, so every existing call site (`collectBodyParts`,
 * `estimateReadingMinutes`, the JSON-LD builder) works unchanged.
 *
 * `mergeArticleMetaOverlay` never overwrites a key that is already present, so
 * this cannot damage an article whose real body the bundle does ship.
 */
export function publishRuntimeArticleBody(id: string, locale: Locale, parts: string[]): number {
  if (parts.length === 0) return 0;
  const translations: Record<string, string> = {};
  parts.forEach((part, i) => { translations[`blog.article.${id}.body${i + 1}`] = part; });
  let added = mergeArticleMetaOverlay(locale, translations);
  // Italian is the fallback every article view falls back to on a missing key.
  if (locale !== 'it') added += mergeArticleMetaOverlay('it', translations);
  return added;
}

// ── the orchestrator the router-facing caller uses ──────────────────────────

export interface AdoptedArticle {
  id: string;
  slugs: Partial<Record<Locale, string>>;
  /**
   * True only when the SPA has everything it needs to render this article:
   * the index record AND a body. False means "keep the static HTML".
   */
  renderable: boolean;
}

/**
 * Resolve an unknown article URL and, when possible, make it renderable.
 *
 * Returns `null` when the id itself could not be resolved — the caller then has
 * nothing to do but leave the page as the shard served it.
 *
 * `renderable: false` is the other fail-open exit: we know WHICH article this
 * is (enough for canonical URLs, hreflang and analytics) but not enough to draw
 * it, so the static HTML must stay. Taking over with a title and an empty body
 * would be strictly worse than the page we found.
 */
export async function adoptRuntimeArticle(
  section: OverlaySection,
  locale: Locale,
  slug: string,
  opts: { bodyParts?: string[] } = {},
): Promise<AdoptedArticle | null> {
  const resolved = await resolveArticleBySlug(section, locale, slug).catch(() => null);
  if (!resolved) return null;

  rememberRecord(section, resolved.record);
  if (resolved.record) {
    const meta: Record<string, string> = { [`blog.article.${resolved.id}.title`]: resolved.record.title };
    if (resolved.record.excerpt) meta[`blog.article.${resolved.id}.excerpt`] = resolved.record.excerpt;
    mergeArticleMetaOverlay(locale, meta);
    if (locale !== 'it') mergeArticleMetaOverlay('it', meta);
  }

  const parts = opts.bodyParts ?? articleBodyPartsFromStaticArticle(staticArticleElement());
  publishRuntimeArticleBody(resolved.id, locale, parts);

  return {
    id: resolved.id,
    slugs: resolved.slugs,
    renderable: !!resolved.record && parts.length > 0,
  };
}
