name = "astro-staging"
main = "src/worker.js"
compatibility_date = "2025-01-01"
workers_dev = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "frontaliereticino-staging"

[observability]
enabled = true
